[metadata]
name = CF
version = 1.0
author = Kim Vallée, Adel Sohbi
author_email = kim.vallee@polytechnique.edu, adel.sohbi@gmail.com
description = A package for computing the Contextual Fraction and more
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Kim-Vallee/contextual-fraction
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: Apache License 2.0
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src